### ISSUE TITLE
SQLite3::SQLException: no such table

### ISSUE THREAD

**Issue by Donnadieu** [learn-co-curriculum/activerecord-tvshow#34]
On `Full Stack Web Development V6: Advanced Finding Lab`

```Failures:

  1) Show attributes has data attributes given to it from a migration file
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: @rick_and_morty = Show.create(:name => "Rick and Morty", :day => "Thursday", :network => "Adult Swim", :rati
ng => 10)

          ActiveRecord::StatementInvalid:
            Could not find table 'shows'
          # /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/sqlite3_adapter.rb:50

1:in `table_structure'
          # /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/sqlite3_adapter.rb:37
5:in `columns'
          # /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/schema_cache.rb:43:in
 `columns'
          # /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/attributes.rb:93:in `columns'
          # /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/attributes.rb:98:in `columns_hash'
          # /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/inheritance.rb:205:in `subclass_from_attr
ibutes?'
          # /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/inheritance.rb:54:in `new'
          # /home/donnadieu/.rvm/gems/ruby-2.6.0/gems/activerecord-4.2.11/lib/active_record/persistence.rb:33:in `create'
          # ./spec/show_spec.rb:10:in `block (2 levels) in <top (required)>'
```

Steps to recreate:

1. Clone master branch
2. Create app/models/show.rb

```
class Show < ActiveRecord::Base

end
```
3. Create db/migrate/001_create_shows.rb
```
class CreateShows < ActiveRecord::Migration
  def change
    create_table :shows do |t|
      t.string :name
      t.string :day
      t.string :network
      t.integer :rating
    end
  end
end
```
4. Create db/migrate/002_add_season_to_shows.rb
```
class AddSeasonToShows < ActiveRecord::Migration
  def change
    add_column :shows, :season, :string
  end
end
```
5. Run `rspec`

Solution:

On line `9` in `Rakefile` change this:
`ActiveRecord::Migration.migrate("db/migrate/")`

To this:

`ActiveRecord::Migrator.migrate("db/migrate/")`

**Comment by telegraham** [comment]
I just had a student run into this today.

**Comment by Donnadieu** [comment]
Were you able to resolve this with the above suggested fix?

**Comment by maxwellbenton** [comment]
Hi @Donnadieu,

Thank you for spotting this issue and providing thorough feedback. We've updated this lesson to rely on sinatra/activerecord rather than activerecord, and changed the contents of the Rakefile in the proces. This issue should no longer occur for students.

Thank you for contributing to a Learn lesson!
